apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nats
  labels:
    app: title
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nats
  template:
    metadata:
      name: my-nats
      labels:
        app: my-nats
    spec:
      containers:
        - name: my-nats
          image: nats:2.6.6-alpine3.14
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitoring
      restartPolicy: Always
      