apiVersion: v1
kind: Service
metadata:
  name: my-nats
spec:
  selector:
    app: my-nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitoring
      port: 8222
      targetPort: 8222