apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
configMapGenerator:
- literals:
  - MODE=log-only
  name: broadcaster-config
generatorOptions:
  disableNameSuffixHash: true
images:
- name: europe-west4-docker.pkg.dev/dauntless-glow-470207-m2/my-repository/broadcaster-service
  newTag: 98805ff47cbd5fc3c3b9b6498a42664ce62b69d4
- name: europe-west4-docker.pkg.dev/dauntless-glow-470207-m2/my-repository/frontend
  newTag: 98805ff47cbd5fc3c3b9b6498a42664ce62b69d4
- name: europe-west4-docker.pkg.dev/dauntless-glow-470207-m2/my-repository/image-service
  newTag: 98805ff47cbd5fc3c3b9b6498a42664ce62b69d4
- name: europe-west4-docker.pkg.dev/dauntless-glow-470207-m2/my-repository/todo-service
  newTag: 98805ff47cbd5fc3c3b9b6498a42664ce62b69d4
