apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: production
  name: todo-db-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: postgres:15
              env:
                - name: POSTGRES_DB
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_DB
                - name: POSTGRES_USER
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_PASSWORD
              command: [ "/bin/sh", "-c" ]
              args:
                - |
                  BACKUP_FILE="/shared/todo-db-backup-$(date +%Y-%m-%d-%H%M%S).sql"
                  echo "Starting database dump..."
                  PGPASSWORD=${POSTGRES_PASSWORD} \
                    pg_dump -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h postgres-svc -f "${BACKUP_FILE}"
                  echo "Backup complete: ${BACKUP_FILE}"
              volumeMounts:
                - name: backup-volume
                  mountPath: /shared
              readinessProbe:
                exec:
                  command:
                    - pg_isready
                    - -U
                    - postgres
                initialDelaySeconds: 5
                periodSeconds: 5

            - name: gcloud-upload
              image: google/cloud-sdk:latest
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/gcs-credentials.json
                - name: BUCKET_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: BUCKET_NAME
              command: [ "/bin/sh", "-c" ]
              args:
                - |
                  gcloud auth activate-service-account --key-file=/secrets/gcs-credentials.json >/dev/null 2>&1
                  
                  while [ -z "$(ls -A /shared/todo-db-backup-*.sql 2>/dev/null)" ]; do
                    sleep 5
                  done
                  
                  LATEST_BACKUP=$(ls -t /shared/todo-db-backup-*.sql | head -n 1)
                  echo "Uploading $LATEST_BACKUP to bucket ${BUCKET_NAME}..."
                  gsutil cp "$LATEST_BACKUP" gs://${BUCKET_NAME}/
                  echo "Upload complete"
              volumeMounts:
                - name: backup-volume
                  mountPath: /shared
                - name: gcs-credentials-volume
                  mountPath: /secrets
                  readOnly: true
              readinessProbe:
                exec:
                  command:
                    - gsutil
                    - ls
                    - gs://${BUCKET_NAME}/
                initialDelaySeconds: 5
                periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          volumes:
            - name: backup-volume
              emptyDir: { }
            - name: gcs-credentials-volume
              secret:
                secretName: gcs-credentials
                items:
                  - key: gcs-credentials.json
                    path: gcs-credentials.json

          restartPolicy: OnFailure