apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: frontend
          image: europe-west4-docker.pkg.dev/dauntless-glow-470207-m2/my-repository/frontend
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
          env:
            - name: IMAGE_SERVICE_PORT
              value: "3000"
            - name: PROD
              value: "true"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 2
