apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-todo-cronjob
  labels:
    app: random-todo-cronjob
spec:

  schedule: "0 * * * *" # Every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
            - key: "kubernetes.io/arch"
              operator: "Equal"
              value: "amd64"
              effect: "NoSchedule"
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: curl
              image: curlimages/curl:8.4.0
              args:
                - /bin/sh
                - -c
                - |
                  curl -X POST http://todo-service-svc:2346/api/todos/random
              readinessProbe:
                httpGet:
                  path: /api/todos/db-health
                  port: 3001
                initialDelaySeconds: 5
                periodSeconds: 5
                failureThreshold: 3
          restartPolicy: OnFailure
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"