apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster-service
  template:
    metadata:
      labels:
        app: broadcaster-service
    spec:
      containers:
        - name: broadcaster-service
          image: europe-west4-docker.pkg.dev/dauntless-glow-470207-m2/my-repository/broadcaster-service
          env:
            - name: MODE
              valueFrom:
                configMapKeyRef:
                  name: broadcaster-config
                  key: MODE
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: NATS_URL
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
