apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  labels:
    app: image-service
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      name: image-service
      labels:
        app: image-service
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: image-service
          image: europe-west4-docker.pkg.dev/dauntless-glow-470207-m2/my-repository/image-service
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: GIN_MODE
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: ALLOWED_ORIGINS
            - name: CACHE_DURATION_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: CACHE_DURATION_MINUTES
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: IMAGE_URL
            - name: IMAGE_DIR
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: IMAGE_DIR
            - name: CACHED_IMAGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: CACHED_IMAGE_NAME
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
