apiVersion: v1
kind: Service
metadata:
  name: image-service-svc
spec:
  selector:
    app: image-service
  ports:
    - protocol: TCP
      targetPort: 3000
      name: http
      port: 2345
  type: ClusterIP
  